use_frameworks!

target 'DynamicRouter_Example' do
  pod 'DynamicRouter', :path => '../'

  target 'DynamicRouter_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
